### ISSUE TITLE
Does not stay on top after reboot

### ISSUE THREAD

**Issue by simone-omniaweb** [markiewb/showbreadcrumbsattop#2]
After each time I restart Netbeans, the breadcrumbs are back again at the bottom. To have them back to the top I have to disable the plugin, restart, enable the plugin, restart again, and then breadcrumbs are on top again. After the next restart, again at the bottom.

Product Version: NetBeans IDE 8.2 (Build 201609300101)
Java: 1.8.0_101; Java HotSpot(TM) 64-Bit Server VM 25.101-b13
Runtime: Java(TM) SE Runtime Environment 1.8.0_101-b13
System: Windows 10 version 10.0 running on amd64; Cp1252; it_IT (nb)

**Comment by ntls** [comment]
Same here.

Product Version: NetBeans IDE 8.2 (Build 201609300101)
Java: 1.8.0_111; Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
Runtime: Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
System: Ubuntu 16.04 kernel: 4.4.0-45-generic

**Comment by markiewb** [comment]
@ntls @simone-omniaweb Please try https://github.com/markiewb/showbreadcrumbsattop/releases/tag/v1.0.2 and give me feedback!

**Comment by simone-omniaweb** [comment]
For me it works. Thanks!

**Comment by ntls** [comment]
Same here, it works! Thank you

**Comment by markiewb** [comment]
Thanks for the feedback. I will push this version to the plugin center.
